FROM ghcr.io/astral-sh/uv:python3.14-bookworm-slim

RUN apt-get update && apt-get install -y --no-cache \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app/

COPY pyproject.toml /app/
COPY uv.lock /app/
RUN uv sync

COPY . /app/

CMD ["uv", "run", "python", "main.py"]
